export const dummyData = [
  {
    id: 1,
    firstname: "Kesavan",
    jobtitle: "-",
    username: 75123,
    email: "kesavan@inc.com",
    contactNumber: 8075423337,
    EmployementID: "222",
    EmploymentType: "god",
    VeteranStatus: "Inactive",
    Gender: "male",
    payrollID: "-",
    WorkerID: 2,
    classifaction: "billable",
  },
  {
    id: 2,
    firstname: "Akash",
    username: 75124,
    email: "	akash@inc.com",
    contactNumber: 9629653377,
    EmployementID: "-",
    EmploymentType: "-",
    VeteranStatus: "Active",
    Gender: "-",
    payrollID: "-",
    WorkerID: 5,
    classifaction: "bilable",
  },
  {
    id: 3,
    firstname: "Naveen Kumar",
    username: 75125,
    email: "	naveen@inc.com",
    contactNumber: 902965723,
    EmployementID: "-",
    EmploymentType: "-",
    VeteranStatus: "Inactive",
    Gender: "-",
    payrollID: "-",
    WorkerID: 0,
    classifaction: "bilable",
  },
  {
    id: 4,
    firstname: "Arun Prakash",
    username: 75126,
    email: "arun@inc.com",
    contactNumber: 9945687219,
    EmployementID: "-",
    EmploymentType: "-",
    VeteranStatus: "Active",
    Gender: "-",
    payrollID: "-",
    WorkerID: 3,
    classifaction: "bilable",
  },
  {
    id: 5,
    firstname: "Manoj",
    username: 75127,
    email: "manoj@inc.com",
    contactNumber: 9956231245,
    EmployementID: "-",
    EmploymentType: "-",
    VeteranStatus: "Active",
    Gender: "-",
    payrollID: "-",
    WorkerID: 2,
    classifaction: "bilable",
  },
  {
    id: 6,
    firstname: "Vishnu",
    username: 75128,
    email: "vishnu@inc.com",
    contactNumber: 9366144319,
    EmployementID: "-",
    EmploymentType: "-",
    VeteranStatus: "Inactive",
    Gender: "-",
    payrollID: "-",
    WorkerID: 1,
    classifaction: "bilable",
  },
  {
    id: 7,
    firstname: "Varun",
    username: 75129,
    email: "varun@inc.com",
    contactNumber: 9098644319,
    EmployementID: "-",
    EmploymentType: "-",
    VeteranStatus: "Active",
    Gender: "-",
    payrollID: "-",
    WorkerID: 6,
    classifaction: "bilable",
  },
  {
    id: 8,
    firstname: "Raj",
    username: 75130,
    email: "raj@inc.com",
    contactNumber: 9956238472,
    EmployementID: "-",
    EmploymentType: "-",
    VeteranStatus: "Inactive",
    Gender: "-",
    payrollID: "-",
    WorkerID: 3,
    classifaction: "bilable",
  },
  {
    id: 9,
    firstname: "Guru",
    username: 75131,
    email: "guru@inc.com",
    contactNumber: 9875461320,
    EmployementID: "-",
    EmploymentType: "-",
    VeteranStatus: "Inactive",
    Gender: "-",
    payrollID: "-",
    WorkerID: 0,
    classifaction: "bilable",
  },
  {
    id: 10,
    firstname: "Gowtham",
    username: 75132,
    email: "gowtham@inc.com",
    contactNumber: 9078654219,
    EmployementID: "-",
    EmploymentType: "-",
    VeteranStatus: "Active",
    Gender: "-",
    payrollID: "-",
    WorkerID: 7,
    classifaction: "bilable",
  },
  {
    id: 11,
    firstname: "Vijay",
    username: 75133,
    email: "Vijay@inc.com",
    contactNumber: 9944421563,
    EmployementID: "-",
    EmploymentType: "-",
    VeteranStatus: "Active",
    Gender: "-",
    payrollID: "-",
    WorkerID: 3,
    classifaction: "bilable",
  },
  {
    id: 12,
    firstname: "Ilango",
    username: 75134,
    email: "Ilango@23.com",
    contactNumber: 9978423105,
    EmployementID: "-",
    EmploymentType: "-",
    VeteranStatus: "Inactive",
    Gender: "-",
    payrollID: "-",
    WorkerID: 2,
    classifaction: "bilable",
  },
  {
    id: 13,
    firstname: "Sam",
    username: 75136,
    email: "samoff@w.com",
    contactNumber: 6396857412,
    EmployementID: "-",
    EmploymentType: "-",
    VeteranStatus: "Inactive",
    Gender: "-",
    payrollID: "-",
    WorkerID: 3,
    classifaction: "bilable",
  },
  {
    id: 14,
    firstname: "Dinesh",
    username: 75137,
    email: "dine24@.com",
    contactNumber: 9023105648,
    EmployementID: "-",
    EmploymentType: "-",
    VeteranStatus: "Inactive",
    Gender: "-",
    payrollID: "-",
    WorkerID: 6,
    classifaction: "bilable",
  },
  {
    id: 15,
    firstname: "Chakravarthy",
    username: 75138,
    email: "akv@90.com",
    contactNumber: 9889564219,
    EmployementID: "-",
    EmploymentType: "-",
    VeteranStatus: "Active",
    Gender: "-",
    payrollID: "-",
    WorkerID: 2,
    classifaction: "bilable",
  },
  {
    id: 16,
    firstname: "Prerna",
    username: 75139,
    email: "prernaof@inc.com",
    contactNumber: 9876543210,
    EmployementID: "-",
    EmploymentType: "-",
    VeteranStatus: "Active",
    Gender: "-",
    payrollID: "-",
    WorkerID: 8,
    classifaction: "bilable",
  },
  {
    id: 17,
    firstname: "Irin",
    username: 75140,
    email: "iamIrin@inc.com",
    contactNumber: 9845321670,
    EmployementID: "-",
    EmploymentType: "-",
    VeteranStatus: "Inactive",
    Gender: "-",
    payrollID: "-",
    WorkerID: 4,
    classifaction: "bilable",
  },

  {
    id: 18,
    firstname: "Joyal",
    username: 75141,
    email: "jo77@.com",
    contactNumber: 9012795436,
    EmployementID: "-",
    EmploymentType: "-",
    VeteranStatus: "Active",
    Gender: "-",
    payrollID: "-",
    WorkerID: 2,
    classifaction: "bilable",
  },
  {
    id: 19,
    firstname: "Mohamad",
    username: 75142,
    email: "mohaMD202@.com",
    contactNumber: 9820346858,
    EmployementID: "-",
    EmploymentType: "-",
    VeteranStatus: "Active",
    Gender: "-",
    payrollID: "-",
    WorkerID: 3,
    classifaction: "bilable",
  },
  {
    id: 20,
    firstname: "Praveen",
    username: 75143,
    email: "praveen@.com",
    contactNumber: 6345128796,
    EmployementID: "-",
    EmploymentType: "-",
    VeteranStatus: "Active",
    Gender: "-",
    payrollID: "-",
    WorkerID: 3,
    classifaction: "bilable",
  },
  {
    id: 21,
    firstname: "Nandha Kumar",
    username: 75144,
    email: "nkOfficial@.com",
    contactNumber: 7386459213,
    EmployementID: "-",
    EmploymentType: "-",
    VeteranStatus: "Inactive",
    Gender: "-",
    payrollID: "-",
    WorkerID: 1,
    classifaction: "bilable",
  },
  {
    id: 22,
    firstname: "Mani",
    username: 75145,
    email: "mani@gmail.com",
    contactNumber: 9043513609,
    EmployementID: "-",
    EmploymentType: "-",
    VeteranStatus: "Active",
    Gender: "-",
    payrollID: "-",
    WorkerID: 0,
    classifaction: "bilable",
  },
  {
    id: 23,
    firstname: "Harish",
    username: 75146,
    email: "hari12@.com",
    contactNumber: 6321302306,
    EmployementID: "-",
    EmploymentType: "-",
    VeteranStatus: "Active",
    Gender: "-",
    payrollID: "-",
    WorkerID: 5,
    classifaction: "bilable",
  },
  {
    id: 24,
    firstname: "Vasudev Menon",
    username: 75147,
    email: "VasuM7@.com",
    contactNumber: 7300886612,
    EmployementID: "-",
    EmploymentType: "-",
    VeteranStatus: "Inactive",
    Gender: "-",
    payrollID: "-",
    WorkerID: 3,
    classifaction: "bilable",
  },
  {
    id: 25,
    firstname: "Salmon",
    username: 75147,
    email: "salmonS@gmail.com",
    contactNumber: 9923105764,
    EmployementID: "-",
    EmploymentType: "-",
    VeteranStatus: "Inactive",
    Gender: "-",
    payrollID: "-",
    WorkerID: 2,
    classifaction: "bilable",
  },
];
